### ISSUE TITLE
In App Updater just working with opened PS

### ISSUE THREAD

**Issue by lucazin** [dnKaratzas/android-inapp-update#6] opened 2020-01-04 11:15 UTC
Hi!

AppUpdate lib is great! congrats!

But im stucked in this problem! Just open the immediate update is the user open the playstore and looking for updates.. after that start working.

But if he dont look for updates in playstore?

**Comment by dnKaratzas** [comment] 2020-01-07 11:07
Updated the Core Play library to the latest version. Cannot test it right now. If you can please check if the update fixed this issue.

**Comment by krishna4741** [comment] 2020-02-10 07:13
Hello,
Its working fine,
The issue is after installing latest update from play store, it again give me pop-up that app update available, in recursive manner. 
How to solve this.

**Comment by dnKaratzas** [comment] 2020-03-16 11:03
Latest version resolve that issue. 
Duplicate of #5

**Comment by dnKaratzas** [comment] 2020-03-18 09:58
Recieved response:

> Status: Won't Fix (Intended Behavior)
> 
> Thanks for reporting,
> 
> the Update Availability is currently refreshed periodically or when you visit the "My Apps & Games" page. So the observed behaviour is intended.
> 
> If you are testing your integration, you can trigger the refresh manually, see https://developer.android.com/guide/playcore/in-app-updates#troubleshoot
> 
> Note: this will not be a problem for your users, since their device will receive the updated availability during the next periodic refresh.
>

**Comment by dnKaratzas** [comment] 2020-03-18 10:00
Regarding the response if the issue it is a normal behavior.

**Closed by dnKaratzas** 2020-03-18 10:00 UTC
